/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_josephmoscoso;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Joseph
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_admin = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_empleados = new javax.swing.JTree();
        jLabel4 = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jd_registrar = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf_nombre = new javax.swing.JTextField();
        fechan = new com.toedter.calendar.JDateChooser();
        tf_user = new javax.swing.JTextField();
        tf_pass = new javax.swing.JPasswordField();
        tf_correo = new javax.swing.JTextField();
        cb_puesto = new javax.swing.JComboBox<>();
        menuem = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        Visualizar = new javax.swing.JMenuItem();
        visualizarem = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tf_nombre1 = new javax.swing.JTextField();
        tf_user1 = new javax.swing.JTextField();
        tf_pass1 = new javax.swing.JPasswordField();
        tf_correo1 = new javax.swing.JTextField();
        fecham = new javax.swing.JTextField();
        puestom = new javax.swing.JTextField();
        modificarem = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jd_dulceria = new javax.swing.JDialog();
        registrar2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_dulces1 = new javax.swing.JTree();
        jLabel28 = new javax.swing.JLabel();
        jd_peliculas = new javax.swing.JDialog();
        jd_aseo = new javax.swing.JDialog();
        registrar1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_aseo = new javax.swing.JTree();
        jLabel22 = new javax.swing.JLabel();
        dulcesreg = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        tf_nombre2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tf_sabor = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cb_categdul = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        menudul = new javax.swing.JPopupMenu();
        dul_visualizar = new javax.swing.JMenuItem();
        dul_eliminar = new javax.swing.JMenuItem();
        dul_modificar = new javax.swing.JMenuItem();
        jd_visualizardul = new javax.swing.JDialog();
        tf_nombre3 = new javax.swing.JTextField();
        tf_user2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        fecham1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jd_modificardul = new javax.swing.JDialog();
        jLabel33 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        regaseo = new javax.swing.JDialog();
        jLabel34 = new javax.swing.JLabel();
        tf_nombre4 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cb_aseo = new javax.swing.JComboBox<>();
        jButton12 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_descripcion = new javax.swing.JTextArea();
        menuaseo = new javax.swing.JPopupMenu();
        dul_visualizar1 = new javax.swing.JMenuItem();
        dul_eliminar1 = new javax.swing.JMenuItem();
        dul_modificar1 = new javax.swing.JMenuItem();
        visase = new javax.swing.JDialog();
        fecham2 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        tf_nombre5 = new javax.swing.JTextField();
        tf_user3 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jd_md = new javax.swing.JDialog();
        jLabel42 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_ui = new javax.swing.JTextField();
        tf_pi = new javax.swing.JPasswordField();
        jb_inicio = new javax.swing.JButton();

        jt_empleados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Empleados");
        jt_empleados.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_empleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_empleados);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Administrador");

        registrar.setText("Agregar empleado");
        registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarMouseClicked(evt);
            }
        });

        jLabel5.setText("Haga click derecho en el jtree para las demas opciones");

        javax.swing.GroupLayout jd_adminLayout = new javax.swing.GroupLayout(jd_admin.getContentPane());
        jd_admin.getContentPane().setLayout(jd_adminLayout);
        jd_adminLayout.setHorizontalGroup(
            jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_adminLayout.createSequentialGroup()
                .addGroup(jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_adminLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(registrar)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_adminLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel5))
                    .addGroup(jd_adminLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_adminLayout.setVerticalGroup(
            jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_adminLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGroup(jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_adminLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(registrar)
                        .addContainerGap(254, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_adminLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Agregar empleado");

        jLabel7.setText("Nombre");

        jLabel8.setText("Fecha de nacimiento");

        jLabel9.setText("User");

        jLabel10.setText("Password");

        jLabel11.setText("Correo");

        jLabel12.setText("puesto");

        jButton1.setText("Registrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        cb_puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dulceria", "Boleteria", "Aseo" }));

        javax.swing.GroupLayout jd_registrarLayout = new javax.swing.GroupLayout(jd_registrar.getContentPane());
        jd_registrar.getContentPane().setLayout(jd_registrarLayout);
        jd_registrarLayout.setHorizontalGroup(
            jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registrarLayout.createSequentialGroup()
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_registrarLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel6))
                    .addGroup(jd_registrarLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombre)
                            .addComponent(fechan, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(tf_user)
                            .addComponent(tf_pass)
                            .addComponent(tf_correo)
                            .addComponent(cb_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_registrarLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButton1)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jd_registrarLayout.setVerticalGroup(
            jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_registrarLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8))
                    .addComponent(fechan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cb_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        menuem.add(Modificar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        menuem.add(Eliminar);

        Visualizar.setText("Visualizar todos los datos");
        Visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarActionPerformed(evt);
            }
        });
        menuem.add(Visualizar);

        jLabel13.setText("Datos del empleado");

        jLabel14.setText("puesto");

        jLabel15.setText("Nombre");

        jLabel16.setText("Fecha de nacimiento");

        jLabel17.setText("User");

        jLabel18.setText("Password");

        jLabel19.setText("Correo");

        tf_nombre1.setEditable(false);

        tf_user1.setEditable(false);

        tf_pass1.setEditable(false);

        tf_correo1.setEditable(false);

        fecham.setEditable(false);

        puestom.setEditable(false);
        puestom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout visualizaremLayout = new javax.swing.GroupLayout(visualizarem.getContentPane());
        visualizarem.getContentPane().setLayout(visualizaremLayout);
        visualizaremLayout.setHorizontalGroup(
            visualizaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizaremLayout.createSequentialGroup()
                .addGroup(visualizaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(visualizaremLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel13))
                    .addGroup(visualizaremLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(visualizaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(visualizaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombre1)
                            .addComponent(tf_user1)
                            .addComponent(tf_pass1)
                            .addComponent(tf_correo1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(fecham)
                            .addComponent(puestom))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        visualizaremLayout.setVerticalGroup(
            visualizaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizaremLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(24, 24, 24)
                .addGroup(visualizaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(visualizaremLayout.createSequentialGroup()
                        .addGroup(visualizaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel16))
                    .addComponent(fecham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(visualizaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_user1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(visualizaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_pass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(visualizaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_correo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(visualizaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(puestom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel20.setText("Seleccione boton correspondiente");

        jButton2.setText("Modificar nombre");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Modificar fecha");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Modificar user");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Modificar contraseña");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Modificar correo");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("Modificar puesto");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout modificaremLayout = new javax.swing.GroupLayout(modificarem.getContentPane());
        modificarem.getContentPane().setLayout(modificaremLayout);
        modificaremLayout.setHorizontalGroup(
            modificaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificaremLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(modificaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificaremLayout.createSequentialGroup()
                        .addGroup(modificaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(modificaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton4)
                                .addComponent(jButton3)))
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificaremLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(113, 113, 113))))
            .addGroup(modificaremLayout.createSequentialGroup()
                .addGroup(modificaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificaremLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel20))
                    .addGroup(modificaremLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(modificaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addComponent(jButton6))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        modificaremLayout.setVerticalGroup(
            modificaremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificaremLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        registrar2.setText("Agregar dulce");
        registrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrar2MouseClicked(evt);
            }
        });

        jLabel27.setText("Haga click derecho en el jtree para las demas opciones");

        jt_dulces1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Dulces");
        jt_dulces1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_dulces1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_dulces1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jt_dulces1);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Dulces");

        javax.swing.GroupLayout jd_dulceriaLayout = new javax.swing.GroupLayout(jd_dulceria.getContentPane());
        jd_dulceria.getContentPane().setLayout(jd_dulceriaLayout);
        jd_dulceriaLayout.setHorizontalGroup(
            jd_dulceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_dulceriaLayout.createSequentialGroup()
                .addGroup(jd_dulceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_dulceriaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(registrar2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_dulceriaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel27))
                    .addGroup(jd_dulceriaLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel28)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_dulceriaLayout.setVerticalGroup(
            jd_dulceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_dulceriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addGroup(jd_dulceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_dulceriaLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(registrar2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_dulceriaLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jd_peliculasLayout = new javax.swing.GroupLayout(jd_peliculas.getContentPane());
        jd_peliculas.getContentPane().setLayout(jd_peliculasLayout);
        jd_peliculasLayout.setHorizontalGroup(
            jd_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_peliculasLayout.setVerticalGroup(
            jd_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        registrar1.setText("Agregar al inventario");
        registrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrar1MouseClicked(evt);
            }
        });

        jLabel21.setText("Haga click derecho en el jtree para las demas opciones");

        jt_aseo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Aseo");
        jt_aseo.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_aseo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_aseoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_aseo);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Aseo");

        javax.swing.GroupLayout jd_aseoLayout = new javax.swing.GroupLayout(jd_aseo.getContentPane());
        jd_aseo.getContentPane().setLayout(jd_aseoLayout);
        jd_aseoLayout.setHorizontalGroup(
            jd_aseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_aseoLayout.createSequentialGroup()
                .addGroup(jd_aseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_aseoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(registrar1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_aseoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel21))
                    .addGroup(jd_aseoLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel22)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_aseoLayout.setVerticalGroup(
            jd_aseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_aseoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addGroup(jd_aseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_aseoLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(registrar1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_aseoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Agregar dulce");

        jLabel24.setText("Nombre");

        jLabel25.setText("Sabor");

        jLabel26.setText("Categoria");

        cb_categdul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chocolates", "Gomitas", "Paletas", "Chicles" }));

        jButton8.setText("Agregar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dulcesregLayout = new javax.swing.GroupLayout(dulcesreg.getContentPane());
        dulcesreg.getContentPane().setLayout(dulcesregLayout);
        dulcesregLayout.setHorizontalGroup(
            dulcesregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dulcesregLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dulcesregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dulcesregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dulcesregLayout.createSequentialGroup()
                        .addGroup(dulcesregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_sabor)
                            .addComponent(tf_nombre2))
                        .addGap(29, 29, 29))
                    .addGroup(dulcesregLayout.createSequentialGroup()
                        .addComponent(cb_categdul, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(dulcesregLayout.createSequentialGroup()
                .addGroup(dulcesregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dulcesregLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel23))
                    .addGroup(dulcesregLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton8)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        dulcesregLayout.setVerticalGroup(
            dulcesregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dulcesregLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(dulcesregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dulcesregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_sabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dulcesregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cb_categdul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        dul_visualizar.setText("Visualizar");
        dul_visualizar.setToolTipText("");
        dul_visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dul_visualizarActionPerformed(evt);
            }
        });
        menudul.add(dul_visualizar);

        dul_eliminar.setText("eliminar");
        dul_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dul_eliminarActionPerformed(evt);
            }
        });
        menudul.add(dul_eliminar);

        dul_modificar.setText("Modificar");
        dul_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dul_modificarActionPerformed(evt);
            }
        });
        menudul.add(dul_modificar);

        tf_nombre3.setEditable(false);

        tf_user2.setEditable(false);

        jLabel29.setText("Datos del dulce");

        jLabel30.setText("Nombre");

        jLabel31.setText("Sabor");

        fecham1.setEditable(false);

        jLabel32.setText("Categoria");

        javax.swing.GroupLayout jd_visualizardulLayout = new javax.swing.GroupLayout(jd_visualizardul.getContentPane());
        jd_visualizardul.getContentPane().setLayout(jd_visualizardulLayout);
        jd_visualizardulLayout.setHorizontalGroup(
            jd_visualizardulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_visualizardulLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jd_visualizardulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_visualizardulLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel29))
                    .addGroup(jd_visualizardulLayout.createSequentialGroup()
                        .addGroup(jd_visualizardulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_visualizardulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombre3, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(fecham1)
                            .addComponent(tf_user2))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jd_visualizardulLayout.setVerticalGroup(
            jd_visualizardulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_visualizardulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(24, 24, 24)
                .addGroup(jd_visualizardulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_visualizardulLayout.createSequentialGroup()
                        .addGroup(jd_visualizardulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(tf_nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel31))
                    .addComponent(fecham1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_visualizardulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tf_user2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel33.setText("Seleccione boton correspondiente");

        jButton9.setText("Modificar nombre");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setText("Modificar sabor");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton11.setText("Modificar categoria");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modificardulLayout = new javax.swing.GroupLayout(jd_modificardul.getContentPane());
        jd_modificardul.getContentPane().setLayout(jd_modificardulLayout);
        jd_modificardulLayout.setHorizontalGroup(
            jd_modificardulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificardulLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jd_modificardulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificardulLayout.createSequentialGroup()
                        .addGroup(jd_modificardulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton11)
                            .addGroup(jd_modificardulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton10)
                                .addComponent(jButton9)))
                        .addGap(14, 14, 14)))
                .addGap(111, 111, 111))
        );
        jd_modificardulLayout.setVerticalGroup(
            jd_modificardulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificardulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("Agregar al inventario");

        jLabel35.setText("Nombre");

        jLabel36.setText("Descripcion");

        jLabel37.setText("Categoria");

        cb_aseo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Limpieza de pisos", "Limpeza de vidrios", "Limpieza de mesas" }));

        jButton12.setText("Agregar");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        ta_descripcion.setColumns(20);
        ta_descripcion.setRows(5);
        jScrollPane4.setViewportView(ta_descripcion);

        javax.swing.GroupLayout regaseoLayout = new javax.swing.GroupLayout(regaseo.getContentPane());
        regaseo.getContentPane().setLayout(regaseoLayout);
        regaseoLayout.setHorizontalGroup(
            regaseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regaseoLayout.createSequentialGroup()
                .addGroup(regaseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regaseoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(regaseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(regaseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(tf_nombre4)))
                    .addGroup(regaseoLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel34))
                    .addGroup(regaseoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_aseo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(regaseoLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton12)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        regaseoLayout.setVerticalGroup(
            regaseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regaseoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addGroup(regaseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tf_nombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(regaseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regaseoLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(72, 72, 72))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(regaseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(cb_aseo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton12)
                .addGap(54, 54, 54))
        );

        dul_visualizar1.setText("Visualizar");
        dul_visualizar1.setToolTipText("");
        dul_visualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dul_visualizar1ActionPerformed(evt);
            }
        });
        menuaseo.add(dul_visualizar1);

        dul_eliminar1.setText("eliminar");
        dul_eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dul_eliminar1ActionPerformed(evt);
            }
        });
        menuaseo.add(dul_eliminar1);

        dul_modificar1.setText("Modificar");
        dul_modificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dul_modificar1ActionPerformed(evt);
            }
        });
        menuaseo.add(dul_modificar1);

        fecham2.setEditable(false);

        jLabel38.setText("Funcion");

        tf_nombre5.setEditable(false);

        tf_user3.setEditable(false);

        jLabel39.setText("Datos del Instrumento");

        jLabel40.setText("Nombre");

        jLabel41.setText("Descripcion");

        javax.swing.GroupLayout visaseLayout = new javax.swing.GroupLayout(visase.getContentPane());
        visase.getContentPane().setLayout(visaseLayout);
        visaseLayout.setHorizontalGroup(
            visaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visaseLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(visaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(visaseLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel39))
                    .addGroup(visaseLayout.createSequentialGroup()
                        .addGroup(visaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(visaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombre5, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(fecham2)
                            .addComponent(tf_user3))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        visaseLayout.setVerticalGroup(
            visaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addGap(24, 24, 24)
                .addGroup(visaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(visaseLayout.createSequentialGroup()
                        .addGroup(visaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(tf_nombre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel41)
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addGroup(visaseLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(fecham2)))
                .addGap(18, 18, 18)
                .addGroup(visaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(tf_user3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jLabel42.setText("Seleccione boton correspondiente");

        jButton13.setText("Modificar nombre");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        jButton14.setText("Modificar descripcion");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        jButton15.setText("Modificar funcion");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_mdLayout = new javax.swing.GroupLayout(jd_md.getContentPane());
        jd_md.getContentPane().setLayout(jd_mdLayout);
        jd_mdLayout.setHorizontalGroup(
            jd_mdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mdLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jd_mdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mdLayout.createSequentialGroup()
                        .addGroup(jd_mdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton14)
                            .addGroup(jd_mdLayout.createSequentialGroup()
                                .addComponent(jButton13)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_mdLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton15)))
                        .addGap(125, 125, 125))
                    .addGroup(jd_mdLayout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(111, 111, 111))))
        );
        jd_mdLayout.setVerticalGroup(
            jd_mdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13)
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addGap(18, 18, 18)
                .addComponent(jButton15)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Inicio Sesion");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        jb_inicio.setText("Iniciar");
        jb_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_inicioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_ui)
                            .addComponent(tf_pi, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jb_inicio)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_pi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jb_inicio)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_inicioMouseClicked
        // TODO add your handling code here:
        if (tf_ui.getText().equals(user) && tf_pi.getText().equals(contra)) {
            if (e.isEmpty()) {
            } else {
                DefaultTreeModel m = (DefaultTreeModel) jt_empleados.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
                for (empleados t : e) {
                    DefaultMutableTreeNode puesto;
                    puesto = new DefaultMutableTreeNode(t.getPuesto());
                    DefaultMutableTreeNode empleado;
                    empleado = new DefaultMutableTreeNode(t);
                    puesto.add(empleado);
                    raiz.add(puesto);
                }
                m.reload();
            }
            jd_admin.setModal(true);
            jd_admin.pack();
            jd_admin.setLocationRelativeTo(this);
            jd_admin.setVisible(true);
        } else {
            for (empleados t : e) {
                if (tf_ui.getText().equals(t.getUser()) && tf_pi.getText().equals(t.getContra())) {
                    if (t.getPuesto().equals("Dulceria")) {
                        if (d.isEmpty()) {
                        } else {
                            DefaultTreeModel m = (DefaultTreeModel) jt_dulces1.getModel();
                            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
                            for (dulces dd : d) {
                                DefaultMutableTreeNode categoria;
                                categoria = new DefaultMutableTreeNode(dd.getCategoria());
                                DefaultMutableTreeNode dulce;
                                dulce = new DefaultMutableTreeNode(dd);
                                categoria.add(dulce);
                                raiz.add(categoria);
                            }
                            m.reload();
                        }
                        jd_dulceria.setModal(true);
                        jd_dulceria.pack();
                        jd_dulceria.setLocationRelativeTo(this);
                        jd_dulceria.setVisible(true);
                    }
                    if (t.getPuesto().equals("Boleteria")) {
                        jd_peliculas.setModal(true);
                        jd_peliculas.pack();
                        jd_peliculas.setLocationRelativeTo(this);
                        jd_peliculas.setVisible(true);
                    }
                    if (t.getPuesto().equals("Aseo")) {
                        jd_aseo.setModal(true);
                        jd_aseo.pack();
                        jd_aseo.setLocationRelativeTo(this);
                        jd_aseo.setVisible(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_jb_inicioMouseClicked

    private void registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarMouseClicked
        // TODO add your handling code here:
        jd_registrar.setModal(true);
        jd_registrar.pack();
        jd_registrar.setLocationRelativeTo(this);
        jd_registrar.setVisible(true);
    }//GEN-LAST:event_registrarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        SimpleDateFormat fo = new SimpleDateFormat("yyyy/MM/dd");
        empleados x = new empleados(tf_nombre.getText(), fo.format(fechan.getDate()), tf_user.getText(), tf_pass.getText(), tf_correo.getText(), (String) cb_puesto.getSelectedItem());
        e.add(x);
        DefaultTreeModel m = (DefaultTreeModel) jt_empleados.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode puesto;
        puesto = new DefaultMutableTreeNode((String) cb_puesto.getSelectedItem());
        DefaultMutableTreeNode empleado;
        empleado = new DefaultMutableTreeNode(x);
        puesto.add(empleado);
        raiz.add(puesto);
        m.reload();
        JOptionPane.showMessageDialog(jd_registrar, "Empleado registrado");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jt_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_empleadosMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = jt_empleados.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_empleados.setSelectionRow(row);
            Object v1 = jt_empleados.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof empleados) {
                emp = (empleados) nodo_seleccionado.getUserObject();
                menuem.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jt_empleadosMouseClicked

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        modificarem.setModal(true);
        modificarem.pack();
        modificarem.setLocationRelativeTo(jd_admin);
        modificarem.setVisible(true);
    }//GEN-LAST:event_ModificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        int responde = JOptionPane.showConfirmDialog(this, "¿Seguro de eliminar?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (responde == JOptionPane.OK_OPTION) {
            DefaultTreeModel m = (DefaultTreeModel) jt_empleados.getModel();
            m.removeNodeFromParent(nodo_seleccionado);
            m.reload();
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void VisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarActionPerformed
        // TODO add your handling code here:
        tf_nombre1.setText(emp.getNombre());
        tf_user1.setText(emp.getUser());
        tf_pass1.setText(emp.getContra());
        tf_correo1.setText(emp.getCorreo());
        fecham.setText(emp.getFecha());
        puestom.setText(emp.getPuesto());
        visualizarem.setModal(true);
        visualizarem.pack();
        visualizarem.setLocationRelativeTo(jd_admin);
        visualizarem.setVisible(true);
    }//GEN-LAST:event_VisualizarActionPerformed

    private void puestomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestomActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_empleados.getModel();
        emp.setNombre(JOptionPane.showInputDialog("Ingrese nombre"));
        m.reload();
        JOptionPane.showMessageDialog(modificarem, "Modificado con exito");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_empleados.getModel();
        emp.setFecha(JOptionPane.showInputDialog("Ingrese fecha"));
        m.reload();
        JOptionPane.showMessageDialog(modificarem, "Modificado con exito");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_empleados.getModel();
        emp.setUser(JOptionPane.showInputDialog("Ingrese user"));
        m.reload();
        JOptionPane.showMessageDialog(modificarem, "Modificado con exito");
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_empleados.getModel();
        emp.setContra(JOptionPane.showInputDialog("Ingrese contraseña"));
        m.reload();
        JOptionPane.showMessageDialog(modificarem, "Modificado con exito");
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_empleados.getModel();
        emp.setCorreo(JOptionPane.showInputDialog("Ingrese correo"));
        m.reload();
        JOptionPane.showMessageDialog(modificarem, "Modificado con exito");
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_empleados.getModel();
        emp.setPuesto(JOptionPane.showInputDialog("Ingrese puesto"));
        m.reload();
        JOptionPane.showMessageDialog(modificarem, "Modificado con exito");
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        dulces dul = new dulces(tf_nombre2.getText(), tf_sabor.getText(), (String) cb_categdul.getSelectedItem());
        d.add(dul);
        DefaultTreeModel m = (DefaultTreeModel) jt_dulces1.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode categoria;
        categoria = new DefaultMutableTreeNode(dul.getCategoria());
        DefaultMutableTreeNode dulce;
        dulce = new DefaultMutableTreeNode(dul);
        categoria.add(dulce);
        raiz.add(categoria);
        m.reload();
        JOptionPane.showMessageDialog(jd_registrar, "Dulce registrado");
    }//GEN-LAST:event_jButton8MouseClicked

    private void jt_aseoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_aseoMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = jt_aseo.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_aseo.setSelectionRow(row);
            Object v1 = jt_empleados.getSelectionPath().getLastPathComponent();
            nodo_seleccionado2 = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado2.getUserObject() instanceof aseo) {
                ase = (aseo) nodo_seleccionado2.getUserObject();
                menuaseo.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jt_aseoMouseClicked

    private void registrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrar1MouseClicked
        // TODO add your handling code here:
        regaseo.setModal(true);
        regaseo.pack();
        regaseo.setLocationRelativeTo(this);
        regaseo.setVisible(true);
    }//GEN-LAST:event_registrar1MouseClicked

    private void registrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrar2MouseClicked
        // TODO add your handling code here:
        dulcesreg.setModal(true);
        dulcesreg.pack();
        dulcesreg.setLocationRelativeTo(this);
        dulcesreg.setVisible(true);
    }//GEN-LAST:event_registrar2MouseClicked

    private void jt_dulces1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_dulces1MouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = jt_dulces1.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_dulces1.setSelectionRow(row);
            Object v1 = jt_dulces1.getSelectionPath().getLastPathComponent();
            nodo_seleccionado1 = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado1.getUserObject() instanceof dulces) {
                duc = (dulces) nodo_seleccionado1.getUserObject();
                menudul.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jt_dulces1MouseClicked

    private void dul_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dul_eliminarActionPerformed
        // TODO add your handling code here:
        int responde = JOptionPane.showConfirmDialog(this, "¿Seguro de eliminar?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (responde == JOptionPane.OK_OPTION) {
            DefaultTreeModel m = (DefaultTreeModel) jt_dulces1.getModel();
            m.removeNodeFromParent(nodo_seleccionado1);
            m.reload();
        }
    }//GEN-LAST:event_dul_eliminarActionPerformed

    private void dul_visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dul_visualizarActionPerformed
        // TODO add your handling code here:
        tf_nombre5.setText(ase.getNombre());
        fecham2.setText(ase.getDescripcion());
        tf_user3.setText(ase.getFuncion());
        jd_visualizardul.setModal(true);
        jd_visualizardul.pack();
        jd_visualizardul.setLocationRelativeTo(this);
        jd_visualizardul.setVisible(true);
    }//GEN-LAST:event_dul_visualizarActionPerformed

    private void dul_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dul_modificarActionPerformed
        // TODO add your handling code here:
        jd_modificardul.setModal(true);
        jd_modificardul.pack();
        jd_modificardul.setLocationRelativeTo(this);
        jd_modificardul.setVisible(true);
    }//GEN-LAST:event_dul_modificarActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_dulces1.getModel();
        duc.setNombre(JOptionPane.showInputDialog("Ingrese nombre"));
        m.reload();
        JOptionPane.showMessageDialog(jd_modificardul, "Modificado con exito");
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_dulces1.getModel();
        duc.setSabor(JOptionPane.showInputDialog("Ingrese sabor"));
        m.reload();
        JOptionPane.showMessageDialog(jd_modificardul, "Modificado con exito");
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_dulces1.getModel();
        duc.setCategoria(JOptionPane.showInputDialog("Ingrese categoria"));
        m.reload();
        JOptionPane.showMessageDialog(jd_modificardul, "Modificado con exito");
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        aseo ase = new aseo(tf_nombre4.getText(), ta_descripcion.getText(), (String) cb_aseo.getSelectedItem());
        a.add(ase);
        DefaultTreeModel m = (DefaultTreeModel) jt_aseo.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode funcion;
        funcion = new DefaultMutableTreeNode(ase.getFuncion());
        DefaultMutableTreeNode producto;
        producto = new DefaultMutableTreeNode(ase);
        funcion.add(producto);
        raiz.add(funcion);
        m.reload();
        JOptionPane.showMessageDialog(regaseo, "Articulo agregado");
    }//GEN-LAST:event_jButton12MouseClicked

    private void dul_visualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dul_visualizar1ActionPerformed
        // TODO add your handling code here:
        tf_nombre3.setText(duc.getNombre());
        fecham1.setText(duc.getSabor());
        tf_user2.setText(duc.getCategoria());
        visase.setModal(true);
        visase.pack();
        visase.setLocationRelativeTo(this);
        visase.setVisible(true);
    }//GEN-LAST:event_dul_visualizar1ActionPerformed

    private void dul_eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dul_eliminar1ActionPerformed
        // TODO add your handling code here:
        int responde = JOptionPane.showConfirmDialog(this, "¿Seguro de eliminar?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (responde == JOptionPane.OK_OPTION) {
            DefaultTreeModel m = (DefaultTreeModel) jt_aseo.getModel();
            m.removeNodeFromParent(nodo_seleccionado2);
            m.reload();
        }
    }//GEN-LAST:event_dul_eliminar1ActionPerformed

    private void dul_modificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dul_modificar1ActionPerformed
        // TODO add your handling code here:
        jd_md.setModal(true);
        jd_md.pack();
        jd_md.setLocationRelativeTo(this);
        jd_md.setVisible(true);
    }//GEN-LAST:event_dul_modificar1ActionPerformed

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_aseo.getModel();
        ase.setNombre(JOptionPane.showInputDialog("Ingrese nombre"));
        m.reload();
        JOptionPane.showMessageDialog(jd_md, "Modificado con exito");
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_aseo.getModel();
        ase.setDescripcion(JOptionPane.showInputDialog("Ingrese descripcion"));
        m.reload();
        JOptionPane.showMessageDialog(jd_md, "Modificado con exito");
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_aseo.getModel();
        ase.setFuncion(JOptionPane.showInputDialog("Ingrese funcion"));
        m.reload();
        JOptionPane.showMessageDialog(jd_md, "Modificado con exito");
    }//GEN-LAST:event_jButton15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JMenuItem Visualizar;
    private javax.swing.JComboBox<String> cb_aseo;
    private javax.swing.JComboBox<String> cb_categdul;
    private javax.swing.JComboBox<String> cb_puesto;
    private javax.swing.JMenuItem dul_eliminar;
    private javax.swing.JMenuItem dul_eliminar1;
    private javax.swing.JMenuItem dul_modificar;
    private javax.swing.JMenuItem dul_modificar1;
    private javax.swing.JMenuItem dul_visualizar;
    private javax.swing.JMenuItem dul_visualizar1;
    private javax.swing.JDialog dulcesreg;
    private javax.swing.JTextField fecham;
    private javax.swing.JTextField fecham1;
    private javax.swing.JTextField fecham2;
    private com.toedter.calendar.JDateChooser fechan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jb_inicio;
    private javax.swing.JDialog jd_admin;
    private javax.swing.JDialog jd_aseo;
    private javax.swing.JDialog jd_dulceria;
    private javax.swing.JDialog jd_md;
    private javax.swing.JDialog jd_modificardul;
    private javax.swing.JDialog jd_peliculas;
    private javax.swing.JDialog jd_registrar;
    private javax.swing.JDialog jd_visualizardul;
    private javax.swing.JTree jt_aseo;
    private javax.swing.JTree jt_dulces1;
    private javax.swing.JTree jt_empleados;
    private javax.swing.JPopupMenu menuaseo;
    private javax.swing.JPopupMenu menudul;
    private javax.swing.JPopupMenu menuem;
    private javax.swing.JDialog modificarem;
    private javax.swing.JTextField puestom;
    private javax.swing.JDialog regaseo;
    private javax.swing.JButton registrar;
    private javax.swing.JButton registrar1;
    private javax.swing.JButton registrar2;
    private javax.swing.JTextArea ta_descripcion;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_correo1;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_nombre2;
    private javax.swing.JTextField tf_nombre3;
    private javax.swing.JTextField tf_nombre4;
    private javax.swing.JTextField tf_nombre5;
    private javax.swing.JPasswordField tf_pass;
    private javax.swing.JPasswordField tf_pass1;
    private javax.swing.JPasswordField tf_pi;
    private javax.swing.JTextField tf_sabor;
    private javax.swing.JTextField tf_ui;
    private javax.swing.JTextField tf_user;
    private javax.swing.JTextField tf_user1;
    private javax.swing.JTextField tf_user2;
    private javax.swing.JTextField tf_user3;
    private javax.swing.JDialog visase;
    private javax.swing.JDialog visualizarem;
    // End of variables declaration//GEN-END:variables
    String user = "admin";
    String contra = "admin";
    ArrayList<empleados> e = new ArrayList();
    ArrayList<dulces> d = new ArrayList();
    ArrayList<peliculas> p = new ArrayList();
    ArrayList<aseo> a = new ArrayList();
    empleados emp;
    dulces duc;
    aseo ase;
    peliculas pelis;
    DefaultMutableTreeNode nodo_seleccionado, nodo_seleccionado1, nodo_seleccionado2, nodo_seleccionado3;
}
